/**
 * Generated API for `convex/`
 *
 * WARNING: This file is auto-generated by Convex. Do not edit.
 *
 * @link https://docs.convex.dev/api/generated-types
 */
import type * as files from "../files.js"
import type * as inspections from "../inspections.js"
import type * as inspections_v2 from "../inspections-v2.js"
import type * as pricing from "../pricing.js"
import type * as ragIntegration from "../ragIntegration.js"
import type * as vinDecoder from "../vinDecoder.js"
import type * as workflows from "../workflows.js"
import type * as workflows_v2 from "../workflows-v2.js"
import type { FunctionReference, GeneratedAPI } from "convex/server"

/**
 * A mapping of all query functions in your Convex project
 */
type Queries = {
  files: typeof files.default
  inspections: typeof inspections.get
  "inspections-v2": typeof inspections_v2.get
  pricing: typeof pricing.getShopSettings
  ragIntegration: typeof ragIntegration.listDocuments
  vinDecoder: typeof vinDecoder.decodeVin
  workflows: typeof workflows.get
  "workflows-v2": typeof workflows_v2.get
}

/**
 * A mapping of all mutation functions in your Convex project
 */
type Mutations = {
  files: typeof files.default
  inspections: typeof inspections.create
  "inspections-v2": typeof inspections_v2.create
  pricing: typeof pricing.updateShopSettings
  ragIntegration: typeof ragIntegration.addDocument
  vinDecoder: typeof vinDecoder.decodeVin
  workflows: typeof workflows.enqueueProcessInspection
  "workflows-v2": typeof workflows_v2.enqueueProcessInspection
}

/**
 * A mapping of all action functions in your Convex project
 */
type Actions = {
  files: typeof files.default
  inspections: typeof inspections.default
  "inspections-v2": typeof inspections_v2.default
  pricing: typeof pricing.default
  ragIntegration: typeof ragIntegration.default
  vinDecoder: typeof vinDecoder.default
  workflows: typeof workflows.default
  "workflows-v2": typeof workflows_v2.default
}

/**
 * A mapping of all scheduled functions in your Convex project
 */
type Scheduled = {
  files: typeof files.default
  inspections: typeof inspections.default
  "inspections-v2": typeof inspections_v2.default
  pricing: typeof pricing.default
  ragIntegration: typeof ragIntegration.default
  vinDecoder: typeof vinDecoder.default
  workflows: typeof workflows.default
  "workflows-v2": typeof workflows_v2.default
}

/**
 * A union of all your Convex functions
 */
export type ApiFromModules = FunctionReference<Queries, Mutations, Actions, Scheduled>

/**
 * A union of all your Convex functions
 */
export type FullApi = GeneratedAPI<ApiFromModules>

/**
 * A reference to the Convex API as a `FullApi` object.
 *
 * `api` provides the data-fetching functions as `api.<moduleName>.<functionName>`.
 * It's recommended to type this as `FullApi` as it provides the best
 * type-safety.
 */
export declare const api: FullApi
